services:
  postgres:
    image: postgres:16
    container_name: zest-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: zest_online_market
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - .pgdata:/var/lib/postgresql/data
